apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dm-milestone2-chart.fullname" . }}-pgadmin
  labels:
    {{- include "dm-milestone2-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: pgadmin
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 10 }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "dm-milestone2-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: pgadmin
  template:
    metadata:
      labels:
        {{- include "dm-milestone2-chart.labels" . | nindent 8 }}
        app.kubernetes.io/component: pgadmin
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: pgadmin
          image: "{{ .Values.pgadmin.image.repository }}:{{ .Values.pgadmin.image.tag }}"
          imagePullPolicy: {{ .Values.pgadmin.image.pullPolicy }}
          env:
            - name: SCRIPT_NAME
              value: "/admin"
            - name: PGADMIN_REPLACE_SERVERS_ON_STARTUP
              value: "True"
            - name: PGPASS_FILE
              value: "/pgpass"
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ include "dm-milestone2-chart.fullname" . }}-pgadmin
                  key: PGADMIN_DEFAULT_EMAIL
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dm-milestone2-chart.fullname" . }}-pgadmin
                  key: PGADMIN_DEFAULT_PASSWORD
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: servers-json
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
              readOnly: true
            - name: pgpass
              mountPath: /pgpass
              subPath: pgpass
              readOnly: true
          {{- with .Values.pgadmin.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: servers-json
          configMap:
            name: {{ include "dm-milestone2-chart.fullname" . }}-pgadmin-servers
        - name: pgpass
          secret:
            secretName: {{ include "dm-milestone2-chart.fullname" . }}-pgadmin-pgpass
