apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dm-milestone2-chart.fullname" . }}-postgres
  labels:
    {{- include "dm-milestone2-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 10 }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "dm-milestone2-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        {{- include "dm-milestone2-chart.labels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "dm-milestone2-chart.fullname" . }}-postgres
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "dm-milestone2-chart.fullname" . }}-postgres
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "dm-milestone2-chart.fullname" . }}-postgres
                  key: POSTGRES_PASSWORD
          ports:
            - name: postgres
              containerPort: {{ .Values.postgres.service.port }}
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          {{- with .Values.postgres.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: data
          {{- if .Values.postgres.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "dm-milestone2-chart.fullname" . }}-postgres
          {{- else }}
          emptyDir: {}
          {{- end }}